#!/usr/bin/node

const request = require('request');

// Get the movie ID from the command line argument
const starWarsapi = process.argv[2];

// Make a request to the Star Wars API
request(starWarsapi, (error, response, body) => {
  if (error) {
    console.error('Error:', error);
    return;
  }

  if (response.statusCode !== 200) {
    console.error('Error:', response.statusCode, response.statusMessage);
    return;
  }

  // Parse the response body as JSON
  const movie  = JSON.parse(body);

  // Print the title of the movie
  console.log(movie.results.characters);
});
